name: Continuous Integration

on: [push, pull_request]

jobs:
  code_style:
    name: Clippy & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets -- -D warnings
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          arg: --workspace --all-targets


