name: Continuous Integration

on: [push, pull_request]

jobs:
  code_style:
    name: Clippy & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets -- -D warnings
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check
  test:
    name: Tests
    runs-on: ubuntu-latest
    outputs:
      test-coverage: target/coverage/coverage.json
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: llvm-tools-preview
      - name: Install grcov
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: grcov
      - name: Run tests
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -Zinstrument-coverage
          LLVM_PROFILE_FILE: "cov-%p-%m.profraw"
        with:
          command: test
          args: --workspace --all-targets
      - name: "Generate coverage"
        run: grcov --ignore-not-existing --binary-path=target/debug/deps -o target/coverage -t html -s . .


