on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:
  fmt:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check cargo fmt
        run: cargo fmt --all -- --check
  
  lints:
    name: Check lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: run tests
        run: cargo test --workspace --all-targets
      - name: run doctests
        run: cargo +nightly test --workspace --doc
