name: Publish on crates.io

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  tests-and-lints:
    uses: rob2309/workflows/.github/workflows/rust-code-check.yaml@master

  publish:
    name: Publish to crates.io
    needs: [tests-and-lints]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Check version consistency
        uses: rob2309/workflows/.github/actions/check-crate-version@master
      - name: Create GitHub Release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
      - name: Run cargo publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CratesIoToken }}
